# version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: comment-db
      POSTGRES_USER: ayaan
      POSTGRES_PASSWORD: ayaan
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgres://ayaan:ayaan@db:5432/comment-db
      JWT_SECRET: ayaan123
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
