databases:
  - name: comment-db
    databaseName: comment_db
    user: ayaan

services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/ayaan-7505/comment-app-docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: comment-db
          property: connectionString
      - key: JWT_SECRET
        value: ayaan123
      - key: PORT
        value: 5000

  - type: web
    name: frontend
    env: docker
    repo: https://github.com/ayaan-7505/comment-app-docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: VITE_BACKEND_URL
        value: https://backend.onrender.com
